# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      golang:
        applies-to: security-updates
        patterns:
          - "golang.org/*"
          - "google.golang.org/*"
      k8s:
        applies-to: security-updates
        patterns:
          - "k8s.io/*"
      spf13:
        applies-to: security-updates
        patterns:
          - "github.com/spf13/*"
    open-pull-requests-limit: 0
